
hook.Add( "AddToolMenuCategories", "CustomCategory", function()
	spawnmenu.AddToolCategory( "Utilities", "Salatis Simple Base", "Salatis Simple Base" )
end )

hook.Add( "PopulateToolMenu", "CustomMenuSettings", function()
	spawnmenu.AddToolMenuOption( "Utilities", "Salatis Simple Base", "ssbServer", "Server", "", "", function( panel )
		panel:ClearControls()
        panel:Help( "Serverside options on SSW Guns" )
		panel:NumSlider( "Recoil Mul", "ssb_recoilmul", 0.5, 5 )
        panel:ControlHelp( "Multiplys the vertical recoil of the gun. 1 by default." )
        panel:NumSlider( "Sway Mul", "ssb_swaymul", 0.25, 5 )
        panel:ControlHelp( "Multiplys the horizontal recoil of the gun. 1 by default." )
	end )

    spawnmenu.AddToolMenuOption( "Utilities", "Salatis Simple Base", "ssbClient", "Client", "", "", function( panel )
		panel:ClearControls()
        panel:Help( "Clientside options on SSW Guns" )
		panel:CheckBox( "Viewbobbing", "ssb_viewbob" )
        panel:ControlHelp( "Does exactly what it does on the tin, making your camera move when you walk. Enabled by default." )
        panel:CheckBox( "ViewPunch", "ssb_viewpunch" )
        panel:ControlHelp( "Makes your camera move when you do certain actions like reload and fire. Enabled by default." )
        panel:CheckBox( "Crosshair", "ssb_crosshair" )
        panel:ControlHelp( "Adds an tiny crosshair to your screen, for debugging sights. Disabled by default, admin only." )
	end )
end )